import Head from "next/head";

export default function NMQ() {
  return (
    <>
      <Head>
        <title>About NMQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>NMQ PAge</h1>
    </>
  );
}
