import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Dog from "../src/Dog";

export default function Home() {
  const [title, setTitle] = useState("Title");

  const onSuccess = (dogURL) => {
    console.log({ dogURL });
    setTitle("Olleeey dog fetched!");
  };

  const onError = (msg) => {
    console.log(msg);
  };

  const updateTitle = (e) => {
    const { value } = e.target;

    setTitle(value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NMQ Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Dog onFetch={onSuccess} onError={onError}>
          <h1>Dog Component Home</h1>
        </Dog>

        <section>
          <h1>{title}</h1>

          <input type="text" defaultValue={title} onChange={updateTitle} />
          <button type="button" onClick={() => setTitle("New Title")}>
            Chane Title
          </button>
        </section>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
